// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Assesment_KartikRohilla.Infrastructure.Entities;

[Table("City")]
public partial class City
{
    [Key]
    public int CityId { get; set; }

    [Required]
    [StringLength(100)]
    public string CityName { get; set; }

    public int? StateId { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<EmployeeMaster> EmployeeMasters { get; set; } = new List<EmployeeMaster>();

    [ForeignKey("StateId")]
    [InverseProperty("Cities")]
    public virtual State State { get; set; }
}