// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Assesment_KartikRohilla.Infrastructure.Entities;

[Table("Country")]
public partial class Country
{
    [Key]
    public int CountryId { get; set; }

    [Required]
    [StringLength(100)]
    public string CountryName { get; set; }

    [InverseProperty("Country")]
    public virtual ICollection<EmployeeMaster> EmployeeMasters { get; set; } = new List<EmployeeMaster>();

    [InverseProperty("Country")]
    public virtual ICollection<State> States { get; set; } = new List<State>();
}