// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Assesment_KartikRohilla.Infrastructure.Entities;
using System.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Assesment_KartikRohilla.Infrastructure.Entities
{
    public partial interface INeosoft_KartikRohillaContextProcedures
    {
        Task<List<AddDataResult>> AddDataAsync(string FirstName, string LastName, string EmailAddress, DateTime? DateOfBirth, int? Age, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_Emp_AddEmployeeResult>> stp_Emp_AddEmployeeAsync(string FirstName, string LastName, int? CountryId, int? StateId, int? CityId, string EmailAddress, string MobileNumber, string PanNumber, string PassportNumber, string ProfileImage, byte? Gender, bool? IsActive, DateOnly? DateOfBirth, DateOnly? DateOfJoinee, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_Emp_CheckColumnValueResult>> stp_Emp_CheckColumnValueAsync(string ColumnName, string Value, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_Emp_CheckDuplicateValueResult>> stp_Emp_CheckDuplicateValueAsync(string ColumnName, string Value, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> stp_Emp_DeleteEmployeeAsync(int? Id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_Emp_GetCitiesResult>> stp_Emp_GetCitiesAsync(int? stateId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_Emp_GetCountriesResult>> stp_Emp_GetCountriesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_Emp_GetEmployeeByIdResult>> stp_Emp_GetEmployeeByIdAsync(int? EmployeeId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_Emp_GetEmployeesResult>> stp_Emp_GetEmployeesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_Emp_GetProfileImageNameResult>> stp_Emp_GetProfileImageNameAsync(int? Id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_Emp_GetStatesResult>> stp_Emp_GetStatesAsync(int? countryId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_Emp_LoginUserResult>> stp_Emp_LoginUserAsync(string EmailAddress, string Password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_Emp_UpdateEmployeeResult>> stp_Emp_UpdateEmployeeAsync(int? RowId, string FirstName, string LastName, int? CountryId, int? StateId, int? CityId, string EmailAddress, string MobileNumber, string PanNumber, string PassportNumber, string ProfileImage, byte? Gender, bool? IsActive, DateOnly? DateOfBirth, DateOnly? DateOfJoinee, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> stp_Emp_UploadImageAsync(int? Id, string ProfilePicture, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
