// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Assesment_KartikRohilla.Infrastructure.Entities;

[Index("EmailAddress", Name = "UQ__LoginUse__49A1474009F272A3", IsUnique = true)]
public partial class LoginUser
{
    [Key]
    public int UserId { get; set; }

    [Required]
    [StringLength(100)]
    public string EmailAddress { get; set; }

    [Required]
    [StringLength(256)]
    public string Password { get; set; }
}