// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Assesment_KartikRohilla.Infrastructure.Entities
{
    public partial class stp_Emp_GetStatesResult
    {
        public int StateId { get; set; }
        public string StateName { get; set; }
    }
}
