// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Assesment_KartikRohilla.Infrastructure.Entities;

[Keyless]
[Table("user3")]
public partial class User3
{
    public int Id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string LastName { get; set; }
}