// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Assesment_KartikRohilla.Infrastructure.Entities;

[Keyless]
[Table("user2")]
public partial class User2
{
    public int Id { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string LastName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EmailAddress { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    public byte? IsDeleted { get; set; }

    public DateOnly? DeletedDate { get; set; }

    public int? Age { get; set; }
}